spring:
  datasource:
    url: "jdbc:postgresql://db:5432/fhir"
    username: jhe-example
    password: insecure-for-demo
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false

hapi:
  fhir:
    reuse_cached_search_results_millis: -1
